### ISSUE TITLE
feat/comment-api

### ISSUE THREAD

**Issue by yoo-jimin127** [MZ-OFFISSU/termterm-FE#94]
코멘트 관련 API 작업
---
## TODO
- [x] POST 나만의 용어 설명 등록
- [ ] PUT 나만의 용어 설명 승인 (관리자)
- [x] PUT 좋아요 취소 (일부 디버깅 필요)
- [x] PUT 좋아요 (일부 디버깅 필요)
- [x] POST 신고하기
- [ ] PUT 신고 처리 완료 (관리자)
