### ISSUE TITLE
feat/curation-api

### ISSUE THREAD

**Issue by yoo-jimin127** [MZ-OFFISSU/termterm-FE#95]
큐레이션 관련 API 연동 작업
---
## TODO
- [ ] 아카이브한 큐레이션들 목록
- [ ] 큐레이션 북마크
- [ ] 큐레이션 상세
- [x] 카테고리별 큐레이션 리스트
- [x] 큐레이션 등록
- [ ] 큐레이션 북마크 취소
