### ISSUE TITLE
feat/folder-api

### ISSUE THREAD

**Issue by yoo-jimin127** [MZ-OFFISSU/termterm-FE#96]
폴더 관련 API 연동 작업
---
## TODO
- [ ] 폴더 삭제
- [ ] 폴더 상세페이지_하나씩 보기
- [ ] 폴더 상세페이지_모아서 보기
- [ ] 폴더 정보 수정
- [ ] 내 폴더 리스트
- [x] 폴더 생성
- [ ] 폴더 관련 정보 모달
- [ ] 폴더에 용어 저장 (아카이빙)
- [ ] 폴더에 용어 삭제 (아카이빙 해제)
- [ ] 홈 화면 - 아카이빙한 용어를 확인해 보세요!
